name: WordPress Playground Preview
description: Automatically add a "Preview in WordPress Playground" button to your pull requests for easy testing of WordPress plugins and themes.


inputs:
  mode:
    type: string
    description: 'How to publish the preview button: `append-to-description` or `comment`'
    default: append-to-description
  playground-host:
    type: string
    description: Base WordPress Playground host URL
    default: https://playground.wordpress.net
  blueprint:
    type: string
    description: Custom WordPress Blueprint as a JSON string. When provided, `plugin-path` and `theme-path` are ignored.
  blueprint-url:
    type: string
    description: 'URL pointing to a remote blueprint. When provided, the Playground link uses `?blueprint-url={url}` directly.'
  plugin-path:
    type: string
    description: Path to plugin directory inside the repository (e.g., `.` for root or `plugins/my-plugin`)
  theme-path:
    type: string
    description: Path to theme directory inside the repository (e.g., `.` for root or `themes/my-theme`)
  description-template:
    type: string
    description: Custom markdown/HTML template for PR descriptions (supports {{VARIABLE_NAME}} interpolation)
  comment-template:
    type: string
    description: Custom markdown/HTML template for PR comments (supports {{VARIABLE_NAME}} interpolation)
  restore-button-if-removed:
    type: boolean
    description: Whether to restore the preview button if removed by PR author (only applies to `append-to-description` mode)
    default: true
  github-token:
    description: >
      GitHub token for updating PRs (defaults to GITHUB_TOKEN). Required permissions:
      `pull-requests: write`, `contents: read`
  pr-number:
    type: string
    description: Pull request number (optional, defaults to context.payload.pull_request.number)
  pr-title:
    type: string
    description: Pull request title (optional, defaults to context.payload.pull_request.title)
  pr-head-ref:
    type: string
    description: Pull request head branch ref (optional, defaults to context.payload.pull_request.head.ref)
  pr-head-sha:
    type: string
    description: Pull request head SHA (optional, defaults to context.payload.pull_request.head.sha)
  pr-base-ref:
    type: string
    description: Pull request base branch ref (optional, defaults to context.payload.pull_request.base.ref)
  pr-body:
    type: string
    description: Pull request body/description (optional, defaults to context.payload.pull_request.body)
  repo-owner:
    type: string
    description: Repository owner (optional, defaults to context.payload.repository.owner)
  repo-name:
    type: string
    description: Repository name (optional, defaults to context.payload.repository.name)
  repo-full-name:
    type: string
    description: Repository full name (optional, defaults to context.payload.repository.full_name)

secrets:
  github-token:
    description: >
      GitHub token for updating PRs (defaults to GITHUB_TOKEN). Required permissions:
      `pull-requests: write`, `contents: read`
    required: false

runs:
  using: 'node20'
  main: 'dist/index.js'

outputs:
  preview-url:
    description: Direct link to the generated WordPress Playground instance.
  blueprint-json:
    description: JSON blueprint (stringified) used for the preview.
  rendered-description:
    description: Markdown/HTML snippet inserted into the PR description.
  rendered-comment:
    description: Markdown/HTML snippet used when posting a comment.
  mode:
    description: Effective preview publishing mode (append-to-description or comment).
  comment-id:
    description: ID of the managed preview comment (if applicable).




