name: 'WP Playground PR Preview'
description: 'A GitHub Action to preview WordPress themes in a playground environment'
inputs:
  github-token:
    description: 'GitHub token'
    required: true
  ref: 
    description: 'git ref SHA'
    required: true
    default: 'HEAD'
  base-branch:
    description: 'The branch with with to compare'
    required: true
    default: 'main'
  single-theme:
    description: 'Whether the repository contains a single theme'
    required: false
    default: "false"
  theme-dir:
    description: 'The directory themes are stored'
    required: false
    default: "."
runs:
  using: 'node20'
  main: 'dist/index.js'