name: 'WP Playground PR Preview'
description: 'A GitHub Action to preview WordPress themes in a playground environment'
inputs:
  github-token:
    description: 'GitHub token'
    required: true
  ref: 
    description: 'git ref SHA'
    required: true
  base-branch:
    description: 'The branch with with to compare'
    required: true
    default: 'main'
runs:
  using: 'node20'
  main: 'dist/index.js'