name: 'WP Playground PR Preview'
description: 'A GitHub Action to preview WordPress themes in a playground environment'
inputs:
  github-token:
    description: 'GitHub token'
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'