name: WordPress Playground Preview
description: Automatically add a "Preview in WordPress Playground" button to your pull requests for easy testing of WordPress plugins and themes.


inputs:
  mode:
    type: string
    description: 'How to publish the preview button: `append-to-description` or `post-comment`'
    default: append-to-description
  playground-host:
    type: string
    description: Base WordPress Playground host URL
    default: https://playground.wordpress.net
  blueprint:
    type: string
    description: Custom WordPress Blueprint as a JSON string. When provided, `plugin-path` and `theme-path` are ignored.
  plugin-path:
    type: string
    description: Path to plugin directory inside the repository (e.g., `.` for root or `plugins/my-plugin`)
  theme-path:
    type: string
    description: Path to theme directory inside the repository (e.g., `.` for root or `themes/my-theme`)
  description-template:
    type: string
    description: Custom markdown/HTML template for PR descriptions (supports {{VARIABLE_NAME}} interpolation)
  comment-template:
    type: string
    description: Custom markdown/HTML template for PR comments (supports {{VARIABLE_NAME}} interpolation)
  restore-button-if-removed:
    type: boolean
    description: Whether to restore the preview button if removed by PR author (only applies to `append-to-description` mode)
    default: true

secrets:
  github-token:
    description: GitHub token for updating PRs (defaults to GITHUB_TOKEN). Required permissions: `pull-requests: write`, `contents: read`
    required: false

runs:
  using: 'node20'
  env:
    INPUT_PREVIEW_MODE: ${{ inputs.mode }}
    INPUT_PLAYGROUND_HOST: ${{ inputs.playground-host }}
    INPUT_BLUEPRINT: ${{ inputs.blueprint }}
    INPUT_PLUGIN_PATH: ${{ inputs.plugin-path }}
    INPUT_THEME_PATH: ${{ inputs.theme-path }}
    INPUT_DESCRIPTION_TEMPLATE: ${{ inputs.description-template }}
    INPUT_COMMENT_TEMPLATE: ${{ inputs.comment-template }}
    INPUT_RESTORE_BUTTON_IF_REMOVED: ${{ inputs.restore-button-if-removed }}
  main: 'dist/index.js'

outputs:
  preview-url: ${{ steps.preview.outputs.preview-url }}
  blueprint-json: ${{ steps.preview.outputs.blueprint-json }}
  rendered-description: ${{ steps.preview.outputs.rendered-description }}
  rendered-comment: ${{ steps.preview.outputs.rendered-comment }}
  mode: ${{ steps.preview.outputs.mode }}
  comment-id: ${{ steps.preview.outputs.comment-id }}
