name: Expose Build Artifact on a Public URL
description: Exposes build artifacts on a public URL via GitHub releases for WordPress Playground preview access

on:
  workflow_call:
    inputs:
      artifact-name:
        description: Name of the GitHub Actions artifact to expose (should match upload-artifact name)
        required: true
        type: string

      artifact-filename:
        description: Filename of the zip file inside the artifact
        required: false
        type: string
        default: 'plugin.zip'

      pr-number:
        description: Pull request number (e.g., `github.event.pull_request.number`)
        required: true
        type: string

      commit-sha:
        description: Commit SHA for unique artifact naming (e.g., `github.sha`)
        required: true
        type: string

      artifacts-to-keep:
        description: Number of most recent artifacts to keep for this PR (use `keep-all` to keep all)
        required: false
        type: string
        default: '2'

      release-tag:
        description: GitHub release tag to use (must already exist)
        required: false
        type: string
        default: 'ci-artifacts'

    outputs:
      artifact-url:
        description: Public download URL for the exposed artifact
        value: ${{ jobs.expose-build-artifact-on-public-url.outputs.artifact-url }}

      artifact-name:
        description: Filename of the exposed artifact (format: pr-NUMBER-SHA.zip)
        value: ${{ jobs.expose-build-artifact-on-public-url.outputs.artifact-name }}

jobs:
  expose-build-artifact-on-public-url:
    name: Expose Build Artifact on a Public URL and Cleanup
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to expose assets on a public URL
    outputs:
      artifact-url: ${{ steps.expose-build-artifact-on-public-url.outputs.url }}
      artifact-name: ${{ steps.expose-build-artifact-on-public-url.outputs.name }}
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}

      - name: Upload artifact to release
        id: expose-build-artifact-on-public-url
        env:
          GH_TOKEN: ${{ github.token }}
          PR_NUMBER: ${{ inputs.pr-number }}
          COMMIT_SHA: ${{ inputs.commit-sha }}
          ARTIFACT_FILENAME: ${{ inputs.artifact-filename }}
          RELEASE_TAG: ${{ inputs.release-tag }}
        run: |
          # Create unique filename for this PR and commit
          ARTIFACT_NAME="pr-${PR_NUMBER}-${COMMIT_SHA}.zip"

          # Rename the downloaded artifact
          mv "$ARTIFACT_FILENAME" "$ARTIFACT_NAME"

          # Upload to the release
          echo "Uploading $ARTIFACT_NAME to $RELEASE_TAG release..."
          gh release upload "$RELEASE_TAG" "$ARTIFACT_NAME" \
            --repo ${{ github.repository }} \
            --clobber

          # Get the download URL
          ARTIFACT_URL="https://github.com/${{ github.repository }}/releases/download/${RELEASE_TAG}/${ARTIFACT_NAME}"

          echo "name=$ARTIFACT_NAME" >> $GITHUB_OUTPUT
          echo "url=$ARTIFACT_URL" >> $GITHUB_OUTPUT
          echo "Artifact uploaded to: $ARTIFACT_URL"

      - name: Cleanup old artifacts for this PR
        env:
          GH_TOKEN: ${{ github.token }}
          PR_NUMBER: ${{ inputs.pr-number }}
          ARTIFACTS_TO_KEEP: ${{ inputs.artifacts-to-keep }}
          RELEASE_TAG: ${{ inputs.release-tag }}
        run: |
          echo "Cleaning up old artifacts for PR #$PR_NUMBER (keeping $ARTIFACTS_TO_KEEP most recent)"

          # Check if cleanup is enabled
          if [ "$ARTIFACTS_TO_KEEP" = "keep-all" ]; then
            echo "ARTIFACTS_TO_KEEP=keep-all, keeping all artifacts for this PR"
            exit 0
          fi

          # Get all artifacts for this PR with timestamps
          gh release view "$RELEASE_TAG" --json assets \
            --jq ".assets[] | select(.name | startswith(\"pr-$PR_NUMBER-\")) | \"\(.created_at)|\(.name)\"" \
            > pr-artifacts.txt || true

          if [ ! -s pr-artifacts.txt ]; then
            echo "No existing artifacts found for PR #$PR_NUMBER"
            exit 0
          fi

          ARTIFACT_COUNT=$(wc -l < pr-artifacts.txt | tr -d ' ')
          echo "Found $ARTIFACT_COUNT total artifact(s) for PR #$PR_NUMBER"

          # If we have fewer artifacts than the limit, nothing to delete
          if [ "$ARTIFACT_COUNT" -le "$ARTIFACTS_TO_KEEP" ]; then
            echo "Artifact count ($ARTIFACT_COUNT) is within limit ($ARTIFACTS_TO_KEEP), no cleanup needed"
            exit 0
          fi

          # Sort by timestamp (newest first)
          sort -r pr-artifacts.txt > pr-artifacts-sorted.txt

          # Process artifacts: keep first N, delete rest
          CURRENT=0
          while IFS='|' read -r timestamp artifact; do
            CURRENT=$((CURRENT + 1))
            if [ $CURRENT -le $ARTIFACTS_TO_KEEP ]; then
              echo "Keeping: $artifact (artifact $CURRENT of $ARTIFACTS_TO_KEEP)"
            else
              echo "Deleting: $artifact (old artifact #$CURRENT)"
              gh release delete-asset "$RELEASE_TAG" "$artifact" --yes || echo "Failed to delete $artifact"
            fi
          done < pr-artifacts-sorted.txt

          echo "Cleanup complete for PR #$PR_NUMBER"
